try {
  a;
} catch (_err) {
  try {
    b;
  } catch (_err2) {
    c;
  }
}